export const MODES = {
  sort_2: { id: 'sort_2', name: '2-Way Sort', directions: ['left', 'right'], groupsPerDirection: 2, glyphsPerGroup: 4, unlockCost: 0, baseDiamonds: 1, heartSafetySeconds: 45, starterTargets: [{ id: 'even', label: 'Even', chance: 0.5, timeSeconds: 35, oddsMultiplier: 1, minHistory: 5, oddsLabel: '1:1' }] },
  sort_3: { id: 'sort_3', name: '3-Way Sort', directions: ['left', 'right', 'up'], groupsPerDirection: 2, glyphsPerGroup: 4, unlockCost: 15, baseDiamonds: 2, heartSafetySeconds: 65, starterTargets: [{ id: 'even', label: 'Even', chance: 0.5, timeSeconds: 50, oddsMultiplier: 1, minHistory: 5, oddsLabel: '1:1' }] },
  sort_4: { id: 'sort_4', name: '4-Way Sort', directions: ['left', 'right', 'up', 'down'], groupsPerDirection: 2, glyphsPerGroup: 4, unlockCost: 30, baseDiamonds: 3, heartSafetySeconds: 90, starterTargets: [{ id: 'even', label: 'Even', chance: 0.5, timeSeconds: 70, oddsMultiplier: 1, minHistory: 5, oddsLabel: '1:1' }] },
};
export const modeList = Object.values(MODES);
export const BET_TIERS = [
  { id: 'half', label: 'Conservative', chance: 0.8, oddsMultiplier: 0.5, minHistory: 5, oddsLabel: '1:2' },
  { id: 'even', label: 'Even', chance: 0.5, oddsMultiplier: 1, minHistory: 8, oddsLabel: '1:1' },
  { id: 'double', label: 'Double', chance: 0.25, oddsMultiplier: 2, minHistory: 10, oddsLabel: '2:1' },
  { id: 'five', label: 'Fivefold', chance: 0.1, oddsMultiplier: 5, minHistory: 15, oddsLabel: '5:1' },
  { id: 'ten', label: 'Tenfold', chance: 0.05, oddsMultiplier: 10, minHistory: 20, oddsLabel: '10:1' },
];
export const STORAGE_KEY = 'gaming-parlor-state-v1';
const CLUB_COST = 1;
const HEART_RESTORE_COST = 5;
export function hashSeed(seed) { let h = 2166136261; for (let i = 0; i < seed.length; i += 1) { h ^= seed.charCodeAt(i); h = Math.imul(h, 16777619); } return h >>> 0; }
export function createRng(seed) { let state = hashSeed(seed) || 1; return () => { state |= 0; state = (state + 0x6d2b79f5) | 0; let t = Math.imul(state ^ (state >>> 15), 1 | state); t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t; return ((t ^ (t >>> 14)) >>> 0) / 4294967296; }; }
export function shuffle(items, rng) { const result = [...items]; for (let i = result.length - 1; i > 0; i -= 1) { const j = Math.floor(rng() * (i + 1)); [result[i], result[j]] = [result[j], result[i]]; } return result; }
export function matchesSelector(item, rule) { const all = (values, req = []) => req.every((x) => values.includes(x)); const none = (values, exc = []) => exc.every((x) => !values.includes(x)); if (rule.kind && item.kind !== rule.kind) return false; if (rule.kinds && !rule.kinds.includes(item.kind)) return false; if (!all(item.tags, rule.requiredTags)) return false; if (!none(item.tags, rule.excludesTags)) return false; if (!all(item.colors, rule.containsColors)) return false; if (!none(item.colors, rule.excludesColors)) return false; if (rule.colorCount !== undefined && item.colors.length !== rule.colorCount) return false; if (rule.exactColors) { const a = [...item.colors].sort(); const b = [...rule.exactColors].sort(); if (a.length !== b.length || !b.every((color, index) => a[index] === color)) return false; } return true; }
export function eligibleItems(items, selector) { return items.filter((item) => matchesSelector(item, selector.selector)); }
function overlapPenalty(item, selectors) { return selectors.filter((selector) => matchesSelector(item, selector.selector)).length; }
export function generateBoard(modeId, seed, items, selectors) { const mode = MODES[modeId]; const rng = createRng(seed); const groupCount = mode.directions.length * mode.groupsPerDirection; const viable = selectors.filter((selector) => eligibleItems(items, selector).length >= mode.glyphsPerGroup); for (let attempt = 0; attempt < 80; attempt += 1) { const chosen = shuffle(viable, rng).slice(0, groupCount); const used = new Set(); const groups = []; let failed = false; for (let i = 0; i < chosen.length; i += 1) { const selector = chosen[i]; const direction = mode.directions[Math.floor(i / mode.groupsPerDirection)]; const candidates = shuffle(eligibleItems(items, selector), rng).filter((item) => !used.has(item.glyph)).sort((a, b) => overlapPenalty(a, chosen) - overlapPenalty(b, chosen)); const selected = candidates.slice(0, mode.glyphsPerGroup); if (selected.length < mode.glyphsPerGroup) { failed = true; break; } selected.forEach((item) => used.add(item.glyph)); groups.push({ id: selector.id, label: selector.label, direction, items: selected }); } if (!failed && used.size === groupCount * mode.glyphsPerGroup) { const queue = shuffle(groups.flatMap((group) => group.items.map((item) => ({ item, direction: group.direction, groupId: group.id }))), rng); return { modeId, seed, groups, queue }; } } throw new Error(`Unable to generate ${mode.name} board`); }
export function percentileAtRun(timeSeconds, entries) { if (!entries.length) return 0.5; return entries.filter((entry) => entry.timeSeconds >= timeSeconds).length / entries.length; }
function quantile(sortedAsc, chanceToBeat) { if (!sortedAsc.length) return 0; const position = chanceToBeat * (sortedAsc.length - 1); const lower = Math.floor(position); const upper = Math.ceil(position); if (lower === upper) return sortedAsc[lower]; const weight = position - lower; return sortedAsc[lower] * (1 - weight) + sortedAsc[upper] * weight; }
export function estimateTargets(modeId, entries) { const mode = MODES[modeId]; const actualCount = entries.filter((entry) => entry.entryType !== 'rest').length; const fallbackEven = mode.starterTargets[0].timeSeconds; const fallbackFactors = { half: 1.2, even: 1, double: 0.8, five: 0.65, ten: 0.55 }; if (entries.length < 5) return BET_TIERS.map((target) => ({ ...target, timeSeconds: Math.max(1, Math.round(fallbackEven * fallbackFactors[target.id])), available: actualCount >= target.minHistory, actualCount })); const sorted = entries.map((entry) => entry.timeSeconds).sort((a, b) => a - b); return BET_TIERS.map((target) => ({ ...target, timeSeconds: Math.max(1, Math.round(quantile(sorted, target.chance))), available: actualCount >= target.minHistory, actualCount })); }
export function heartSafety(modeId, entries) { if (entries.length < 5) return MODES[modeId].heartSafetySeconds; const sorted = entries.map((entry) => entry.timeSeconds).sort((a, b) => a - b); return Math.round(quantile(sorted, 0.65)); }
export function addRoundMemory(state, modeId, timeSeconds, createdAt) { const next = structuredClone(state); const entries = next.gameMemory[modeId].entries; entries.push({ timeSeconds, entryType: 'actual', createdAt, percentileAtRun: percentileAtRun(timeSeconds, entries) }); next.gameMemory[modeId].entries = entries.slice(-20); for (const other of Object.keys(next.unlockedModes)) { if (other === modeId || !next.unlockedModes[other]) continue; const otherEntries = next.gameMemory[other].entries; const worst = otherEntries.length ? Math.max(...otherEntries.map((entry) => entry.timeSeconds)) : MODES[other].heartSafetySeconds; otherEntries.push({ timeSeconds: worst, entryType: 'rest', createdAt }); next.gameMemory[other].entries = otherEntries.slice(-20); } return next; }
export function createClubBet(modeId, offer, stake) { return { modeId, targetId: offer.id, targetSeconds: offer.timeSeconds, oddsMultiplier: offer.oddsMultiplier, oddsLabel: offer.oddsLabel, stake, cost: stake * CLUB_COST }; }
export function spadeCost(scope, owned) { const base = scope === 'global' ? 25 : scope === 'sort_2' ? 8 : scope === 'sort_3' ? 12 : 10; const growth = scope === 'global' ? 1.6 : 1.5; return Math.ceil(base * growth ** owned); }
export function buyClubBet(state, bet) { if (bet.stake <= 0) return { ...state, activeClubBet: null }; if (bet.oddsLabel === '1:2' && bet.stake % 2 !== 0) throw new Error('1:2 wagers must be paid in multiples of 2 Clubs'); if (state.resources.diamonds < bet.cost) throw new Error('Not enough Diamonds'); const next = structuredClone(state); next.resources.diamonds -= bet.cost; next.activeClubBet = bet; return next; }
export function unlockMode(state, modeId) { const mode = MODES[modeId]; if (state.unlockedModes[modeId]) return state; if (state.resources.diamonds < mode.unlockCost) throw new Error('Not enough Diamonds'); const next = structuredClone(state); next.resources.diamonds -= mode.unlockCost; next.unlockedModes[modeId] = true; return next; }
export function buySpade(state, scope) { const cost = spadeCost(scope, state.upgrades.spades[scope]); if (state.resources.diamonds < cost) throw new Error('Not enough Diamonds'); const next = structuredClone(state); next.resources.diamonds -= cost; next.upgrades.spades[scope] += 1; return next; }
export function restoreHeart(state) { if (state.resources.hearts >= state.resources.maxHearts) return state; if (state.resources.diamonds < HEART_RESTORE_COST) throw new Error('Not enough Diamonds'); const next = structuredClone(state); next.resources.diamonds -= HEART_RESTORE_COST; next.resources.hearts += 1; return next; }
export function settleRound(state, modeId, timeSeconds, mistakes, seed, createdAt = new Date().toISOString()) { const entries = state.gameMemory[modeId].entries; const safety = heartSafety(modeId, entries); const actual = entries.filter((entry) => entry.entryType === 'actual').map((entry) => entry.timeSeconds); const newWorst = actual.length > 0 && timeSeconds > Math.max(...actual); const heartsLost = timeSeconds > safety ? (newWorst ? 2 : 1) : 0; const spadeBonus = state.upgrades.spades.global + state.upgrades.spades[modeId]; const basePayout = Math.max(0, MODES[modeId].baseDiamonds + spadeBonus + (heartsLost ? -1 : 0)); const activeBet = state.activeClubBet?.modeId === modeId ? state.activeClubBet : null; const betWinnings = activeBet && timeSeconds <= activeBet.targetSeconds ? activeBet.stake + Math.floor(activeBet.stake * activeBet.oddsMultiplier) : 0; const next = addRoundMemory(state, modeId, timeSeconds, createdAt); next.resources.hearts = Math.max(0, next.resources.hearts - heartsLost); next.resources.diamonds += basePayout + betWinnings; next.activeClubBet = null; next.eventLog = [...next.eventLog, { modeId, timeSeconds, mistakes, seed, createdAt, diamondsDelta: basePayout + betWinnings, heartsDelta: -heartsLost, betWinnings }].slice(-50); return next; }
export function streakDuration(baseMs, streak) { return Math.round(baseMs * (1 - Math.min(0.45, Math.max(0, streak) * 0.03))); }
